#Site
locale: "en-US"
title: "cynolyc.us"
title_sep: " :: "
tagline: Developing Developers
description: "Practical solutions and insights for the accidental developer."
url: https://cynolyc.us
repository: https://github.com/cynolycus/cynolycus.github.io
wpm: 200
author: "Ben Sochor"
author_email: "bmsochor@gmail.com"
google_analytics: UA-110479654-1
github_username:  cynolycus
twitter_username: cynolycus
linkedin_username: bmsochor
#collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  series:
    output: true
    permalink: /series/:title/
#Files
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
header_pages:
  - about.md
  - series.md
include:
  - .htaccess
  - _pages
  - _posts
  - _series
exclude:
  - Gemfile
  - Gemfile.lock
keep_files:

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

theme: minima
show_excerpts: true
#Sass
sass:
    sass_dir: _scss
#Plug-ins
plugins:
  - jekyll-sitemap
